### PR TITLE
Make endpoint configurable.

### PR DESCRIPTION
**Pull request by jward-bw**
Hi, hope you accept external PRs. I'd like to use this crate, but our monitoring stack is configured to have very particular endpoints to serve metrics on. Let me know if you want anything changed.

### CODE REVIEW

**Comment by AlexanderThaller** [comment]
Sorry for some reason my github notifications are broken. I would be open to make the endpoint configurable. I will review the code and let you know. Thank you for the pr!

**Comment by AlexanderThaller** [comment]
Can you run `cargo +nightly fmt --all` on your changes? Otherwise it looks good to me.

**Comment by AlexanderThaller** [comment]
@jward-bw can you run cargo fmt (using nightly)? Can merge after that

**Comment by jward-bw** [comment]
Hey Alexander, thanks for getting back to me. Just got round to checking your comments. I've ran the nightly format and rebased to master. I might look at making non-ASCII usable separately if I find time for it.

**Pull request merged**
