### PR TITLE
Update prometheus crate to latest version (0.9.0).

### PR DESCRIPTION
**Pull request by xaep**

### CODE REVIEW

**Comment by AlexanderThaller** [comment]
Should be easy to fix. Can you update the pullrequest with the changes from pullrequest #6? Should be fine to merge afterwards.

**Comment by xaep** [comment]
Yes, will update in the afternoon

**Comment by xaep** [comment]
Done, PTAL

**Comment by AlexanderThaller** [comment]
Thank you! I can do another release so the changes can be used.

**Pull request merged**
